import bcrypt from "bcryptjs";

const data = {
    user: [
        {
            name: "Solomon",
            email: "admin@example.com",
            password: bcrypt.hashSync("1234567", 8),
            isAdmin: true,
        },
        {
            name: "user",
            email: "user@example.com",
            password: bcrypt.hashSync("1234567", 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            _id: 1,
            name: "Dress",
            category: "Dress",
            image: "/IMG/p1.jpg",
            price: 199,
            countInStock: 10,
            brand: null,
            rating: 2,
            numberOfReviews: 9,
            description: "Brand new",
        },
        {
            _id: 2,
            name: "sweat shirt",
            category: "shirt",
            image: "/IMG/p2.jpg",
            price: 299,
            countInStock: 1,
            brand: "Nike",
            rating: 4,
            numberOfReviews: 10,
            description: "Brand new",
        },
        {
            _id: 3,
            name: "Velvet Dress",
            category: "Dress",
            image: "/IMG/p3.jpg",
            price: 150,
            countInStock: 18,
            brand: null,
            rating: 4.1,
            numberOfReviews: 6,
            description: "Brand new",
        },
        {
            _id: 4,
            name: "Dress",
            category: "Dress",
            image: "/IMG/p4.jpg",
            price: 189,
            countInStock: 13,
            brand: null,
            rating: 1.5,
            numberOfReviews: 8,
            description: "Brand new",
        },
        {
            _id: 5,
            name: "T-shirt",
            category: "T-shirt",
            image: "/IMG/p5.jpg",
            price: 69,
            countInStock: 4,
            brand: null,
            rating: 4.9,
            numberOfReviews: 7,
            description: "Brand new",
        },
        {
            _id: 6,
            name: "T-shirt",
            category: "T-shirt",
            image: "/IMG/p6.jpg",
            price: 99,
            countInStock: 0,
            brand: null,
            rating: 4.9,
            numberOfReviews: 9,
            description: "Brand new",
        },
    ],
};

export default data;
