export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const DETAILS_ORDER_REQUEST = "DETAILS_ORDER_REQUEST";
export const DETAILS_ORDER_SUCCESS = "DETAILS_ORDER_SUCCESS";
export const DETAILS_ORDER_FAIL = "DETAILS_ORDER_FAIL";
